import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CartUI from "@/components/cart/layout/cartUI";
import { CartProvider } from "@/context/cartContext";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col text-foreground`}
      >
        <CartProvider>
          {/* Global centered shell */}
          <div className="flex-1 max-w-6xl mx-auto  px-6 sm:px-8 lg:px-12 w-full py-8 ">
            {/* Global Navbar (constrained) */}
            <Navbar />

            {/* Page content */}
            <main>{children}</main>
          </div>

          {/* Footer (same width rhythm, slightly different bg already handled) */}
          <Footer />

          {/* Cart Overlay */}
          <CartUI />
        </CartProvider>
      </body>
    </html>
  );
}
